import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const HEADER = "<!-- AUTO-GENERATED by gootte — DO NOT EDIT (regenerate: gootte digest) -->\n\n";

/**
 * T7 — digest emit. INV-2 carve-out: 관리대상 `.gootte/` 네임스페이스만 write + `.gitignore` 1줄.
 * cling SoT 문서는 절대 mutate X.
 */
export function emitDigest(repoPath: string, body: string): string {
  const dir = join(repoPath, ".gootte");
  mkdirSync(dir, { recursive: true });
  const file = join(dir, "PLAN.md");
  writeFileSync(file, HEADER + body);
  ensureGitignore(repoPath);
  return file;
}

function ensureGitignore(repoPath: string): void {
  const gi = join(repoPath, ".gitignore");
  const line = ".gootte/";
  const cur = existsSync(gi) ? readFileSync(gi, "utf8") : "";
  if (cur.split("\n").includes(line)) return;
  appendFileSync(gi, (cur && !cur.endsWith("\n") ? "\n" : "") + line + "\n");
}
